tasks:
  - name: Setup Python Virtual Environment
    init: |
      python3.9 -m venv venv
      source venv/bin/activate 
    command: pip install -e .[all] #Install all of the dependencies defined in the setup.py file

vscode:
  extensions:
    - eamodio.gitlens
    - redhat.vscode-yaml
    - editorconfig.editorconfig
    - ms-python.python

image:
  file: .gitpod.Dockerfile