tasks:
  - init: pip install pyyaml jsonschema nose2

vscode:
  extensions:
    - eamodio.gitlens
    - redhat.vscode-yaml
    - editorconfig.editorconfig
    - ms-python.python

image:
  file: .gitpod.Dockerfile